# Generated by Django 4.1.6 on 2023-03-11 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contractor', '0002_alter_contractor_options_alter_contractor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='contractor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='contractor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
