# Generated by Django 4.1.6 on 2023-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0002_contractor_contractor_username_contractor_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_username',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_zipcode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='contractor',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
