# Generated by Django 4.1.6 on 2023-03-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0003_alter_contractor_options_alter_contractor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
