# Generated by Django 4.1.6 on 2023-03-11 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contractor', '0005_contractor_last_login_contractor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
