# Generated by Django 4.1.6 on 2023-03-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0007_contractor_is_active_contractor_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='is_staff',
        ),
    ]
