# Generated by Django 4.1.6 on 2023-03-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0008_remove_contractor_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderStatus',
        ),
    ]
