# Generated by Django 4.1.6 on 2023-03-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customer_user'),
        ('Contractor', '0009_rename_order_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contractor.service'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='tags',
            field=models.ManyToManyField(to='Contractor.tag'),
        ),
    ]
