# Generated by Django 4.1.6 on 2023-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0011_remove_orderstatus_tags_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
