# Generated by Django 4.1.6 on 2023-03-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0012_contractor_is_active_contractor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
