# Generated by Django 4.1.6 on 2023-04-27 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contractor', '0013_remove_orderstatus_customer_delete_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contractors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
