# Generated by Django 4.1.6 on 2023-04-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0015_remove_service_contractors_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
