# Generated by Django 4.1.6 on 2023-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
