# Generated by Django 4.1.6 on 2023-03-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0013_remove_orderstatus_customer_delete_contractor'),
        ('Customer', '0006_customer_is_active_customer_is_staff_customer_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
