# Generated by Django 4.1.6 on 2023-02-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contractor_phone',
            field=models.CharField(default=1111111111, max_length=10),
            preserve_default=False,
        ),
    ]
