# Generated by Django 4.1.6 on 2023-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
