# Generated by Django 4.1.6 on 2023-03-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0002_remove_user_role_user_is_contractor_user_is_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
