# Generated by Django 4.1.6 on 2023-02-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
