# Generated by Django 4.1.6 on 2023-02-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0004_yard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yard',
        ),
    ]
