# Generated by Django 4.1.6 on 2023-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0005_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
