# Generated by Django 4.1.6 on 2023-02-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0007_account_firstname_account_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
